/*

 MAP4B.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Programming\C++\GameBoyJam\MHDemake\sprites\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define Map4bWidth 20
#define Map4bHeight 18
#define Map4bBank 0

extern unsigned char Map4b[];

/* End of MAP4B.H */
