/*

 TEST_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Programming\C++\GameBoyJam\MHDemake\sprites\test.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestMapWidth 20
#define TestMapHeight 18
#define TestMapBank 0

extern unsigned char TestMap[];

/* End of TEST_MAP.H */
